/**
 * PaceWise — social running app powered by GroupWisdom
 * Mounts at /running/*
 *
 * On startup, bootstraps a shared "PaceWise Running Club" project and a
 * project-scoped API key that the browser uses to ingest runs and read insights.
 */
import { Router } from "express";
import {
  getUserByEmail,
  createGroup,
  listGroups,
  addMember,
  listMembers,
  addItem,
  listItems,
  listInsights,
  createProjectApiKey,
  listProjectApiKeys,
  db,
  type Group,
} from "./db.js";
import { queueIncrementalAnalysis } from "./engine.js";

export const runningRouter = Router();

// ── Bootstrap a shared running club project ──────────────────────────────────

const CLUB_NAME = "PaceWise Running Club";
const CLUB_MARKER = "pacewise-running-club-v1";

function ensureClub(): { group: Group; projectKey: string } {
  // Look for an existing club by marker in name
  const all = listGroups();
  let group = all.find((g) => g.name === CLUB_NAME);

  if (!group) {
    group = createGroup(CLUB_NAME);
  }

  // Ensure a project key exists for the frontend
  const keys = listProjectApiKeys(group.id);
  const existing = keys.find((k) => k.name === CLUB_MARKER);
  if (existing) return { group, projectKey: existing.key };

  const newKey = createProjectApiKey(group.id, CLUB_MARKER);
  return { group, projectKey: newKey.key };
}

const { group: CLUB, projectKey: CLUB_KEY } = ensureClub();
export const CLUB_GROUP_ID = CLUB.id;

// ── Routes ────────────────────────────────────────────────────────────────────

/** Config the browser needs to call the v1 API directly */
runningRouter.get("/config", (_req, res) => {
  res.json({
    projectId: CLUB.id,
    projectKey: CLUB_KEY,
    apiBase: "/v1",
  });
});

/** Submit a run — wraps v1 ingest with running-specific structure */
runningRouter.post("/log", express_json_already_parsed, (req, res) => {
  const { runnerName, distance, duration, route, notes, emoji } = req.body ?? {};
  if (!runnerName || !distance) {
    return res.status(400).json({ error: "runnerName and distance required" });
  }

  // Ensure the runner exists as a member
  const members = listMembers(CLUB.id);
  let member = members.find((m) => m.name === runnerName);
  if (!member) {
    member = addMember(CLUB.id, runnerName, "runner");
  }

  const pace = duration && distance
    ? `${Math.floor(duration / distance)}:${String(Math.round((duration / distance % 1) * 60)).padStart(2, "0")} /km`
    : null;

  const title = `${emoji || "🏃"} ${runnerName} ran ${distance} km${route ? ` on ${route}` : ""}`;
  const content = [
    `Runner: ${runnerName}`,
    `Distance: ${distance} km`,
    duration ? `Duration: ${Math.floor(duration / 60)}h ${duration % 60}m` : null,
    pace ? `Pace: ${pace}` : null,
    route ? `Route: ${route}` : null,
    notes ? `Notes: ${notes}` : null,
    `Logged at: ${new Date().toISOString()}`,
  ].filter(Boolean).join("\n");

  const item = addItem(CLUB.id, {
    member_id: member.id,
    type: "note",
    title,
    content,
    source: "api",
  });

  queueIncrementalAnalysis(CLUB.id, item);

  res.status(201).json({ item, member });
});

/** Feed — recent runs with member names */
runningRouter.get("/feed", (_req, res) => {
  const rows = (db.prepare(
    `SELECT i.*, m.name as runner_name
     FROM items i
     LEFT JOIN members m ON m.id = i.member_id
     WHERE i.group_id = ?
     ORDER BY i.created_at DESC
     LIMIT 50`
  ).all(CLUB.id) as any[]);
  res.json({ runs: rows });
});

/** Insights — group wisdom generated by the engine */
runningRouter.get("/insights", (_req, res) => {
  const insights = listInsights(CLUB.id);
  res.json({ insights });
});

/** Stats — leaderboard / totals */
runningRouter.get("/stats", (_req, res) => {
  const items = listItems(CLUB.id);
  const members = listMembers(CLUB.id);

  const totals: Record<string, { count: number; km: number; name: string }> = {};
  for (const item of items) {
    const mid = item.member_id ?? "anon";
    if (!totals[mid]) {
      const m = members.find((m) => m.id === mid);
      totals[mid] = { count: 0, km: 0, name: m?.name ?? "Anonymous" };
    }
    const kmMatch = item.content?.match(/Distance:\s*([\d.]+)\s*km/);
    const km = kmMatch ? parseFloat(kmMatch[1]) : 0;
    totals[mid].count++;
    totals[mid].km += km;
  }

  const leaderboard = Object.values(totals)
    .sort((a, b) => b.km - a.km)
    .slice(0, 10);

  res.json({ leaderboard, totalRuns: items.length });
});

// tiny no-op middleware (body already parsed by app-level express.json)
function express_json_already_parsed(_req: any, _res: any, next: any) { next(); }
